### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by wick3dr0se**
- drop redundant (twice called) $bold & $normal variable defitions
- make functions consistent
- changed update function to update_system; Within changed echo to printf (quicker execution) and called bold and normal styling directly (was already in place) and dropped the uncecesarry `wait` call
- reduced overall lines of code and increased readability

### CODE REVIEW

**Comment by mfn77** [comment]
I will merge this. Like I said I also think that after trying with the hidden output, it's definetely not good.

 I never tought of using `printf` rather than `echo`. I will look into it.

Right now other that optimizing code, I would like a consistent progress bar. I wonder if we can fix the position of it rather than showing it after finishing every line and showing progress within itself with fixed position, like in your gif in the bashbar repo.

**Comment by mfn77** [comment]
@wick3dr0se Also I did not try it in the Arch system but with moving distro control to the end of the script do you think it will work correctly? Since it goes from top to bottom. And I cannot see any mention of  `main`  function in the beginning.

**Comment by mfn77** [comment]
@wick3dr0se Lastly in the shell check it says 

> there is three variables but only 2 arguments

 in the `line 9` but I couldn't understand what argument is missing.

Also it doesn't show questions in the user interactions with this new `yes_reply()` function. As you can see in the added picture and it should accept entry key as a yes but it doesn't. 
Screenshot from 2023-04-13 09-27-10

**Comment by mfn77** [comment]
Okay I fixed the latter. The `yes_reply()` function behave correctly now so don't worry about it.

**Comment by wick3dr0se** [comment]
@mfn77 Sorry I haven't seen this sooner. The line 9 issue must be a typo error or something. I wrote bashbar in modern, shellchecked BASH and @adamprice2 copy and pasted it, so should work as expected. I believe it wasn't catching output from yes_reply because I accidently set it to ${1+[Y/n]: } when it should be ${1:+[Y/n]: }, then it should properly append '[Y/n]:' to the first argument, if it exist

**Comment by mfn77** [comment]
@wick3dr0se No problem of course. I tried to solve it in my way but I don't know if it is the best.

**Comment by wick3dr0se** [comment]
@mfn77
> I tried to solve it in my way but I don't know if it is the best

Well with ${1:+$1 }, you're saying append first argument to first argument when it is set and not null, so it should double the output message. I'll do some more work to it soon; Been a bit busy lately

> Right now other that optimizing code, I would like a consistent progress bar. I wonder if we can fix the position of it rather than showing it after finishing every line and showing progress within itself with fixed position, like in your gif in the bashbar repo

I'll work to implement this. With your screenshot I also thought the same thing. It would be nice to lock this thing to the bottom of the terminal, pretty sure I can do it. I've wrote a few TUI projects in BASH

**Pull request merged**
