### PR TITLE
remove hardcoded paths & combine file processing

### PR DESCRIPTION
**Pull request by wick3dr0se**
I removed the hardcoded pathing because it's a bit overkill and we can also combine multiple arguments with the curly brackets in BASH; Making for less individual calls to those commands and therefore increasing the scripts performance

Just starting with some small changes to see how you feel about them. Next PR I plan to remove subshell executions and other repetitive command calls. I think it's also important to drop all the `cd` commands and call the paths directly, all of the above will increase performance and decrease lines of code

### CODE REVIEW

**Comment by mfn77** [comment]
I thought about cd commands too but decided to leave them just in case something goes wrong.

**Comment by mfn77** [comment]
Also I tought it is better to state paths infront to make it easy I guess I was wrong. Is it bad to hard code paths and just write them openly when it's necessary?

**Comment by wick3dr0se** [comment]
Using `cd` is just an extra step that would only risk creating more issues. The only time I recommend using `cd` is when a program can't run outside of necessary directory itself or your script intends to change directory, that persist after execution

I think hardcoding certain things can be beneficial but renaming the well-known $HOME env to $DIR can cause confusion. The others only have a single use, so hardcoding them doesn't provide any benefit. It would make more sense to explicitly state the paths your configurations were installed to in the README, if you wan't that to be aware at all

**Comment by wick3dr0se** [comment]
@mfn77 Forgot to tag you, so you get notified

**Pull request merged**
